# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FriendGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FriendsRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyToDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('date_time', models.DateTimeField()),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.Diary')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyToReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('date_time', models.DateTimeField()),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.ReplyToDiary')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('content', models.CharField(max_length=128)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.Diary')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=16)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('job', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.User')),
            ],
        ),
        migrations.AddField(
            model_name='share',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.User'),
        ),
        migrations.AddField(
            model_name='replytoreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.User'),
        ),
        migrations.AddField(
            model_name='replytodiary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.User'),
        ),
        migrations.AddField(
            model_name='friendsrelation',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.User'),
        ),
        migrations.AddField(
            model_name='friendsrelation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.FriendGroup'),
        ),
        migrations.AddField(
            model_name='friendgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.User'),
        ),
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.Level'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.User'),
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.User'),
        ),
    ]
